version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "custom-metric-test-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-no9vadhofoha"
s3_prefix = "custom-metric-test-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
