AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CustomMetricFunction
  Sample SAM Template for CustomMetricFunction
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CustomMetricFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
    Policies:
      - Statement: 
        - Sid: CloudWatchMetric
          Effect: 'Allow'
          Action: 
            - "cloudwatch:PutMetricData"
          Resource: '*'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CustomMetricFunction:
    Description: "CustomMetricFunction Lambda Function ARN"
    Value: !GetAtt CustomMetricFunction.Arn
  CustomMetricFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CustomMetricFunction.Arn
