version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ec2-monitoring-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-no9vadhofoha"
s3_prefix = "ec2-monitoring-stack"
region = "us-east-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
